language: python
python:
  - "2.7"

# command to install dependencies
install: 
  - "pip install -r requirements.txt"

# command to run tests
script: 
  - cd src
  - python clockrate.py -c 1 -c 2 -c 4 -c 8
  - python clockrate.py -i 'matrix-solve' -c 64 -c 32 -c 16 -c 8 -c 4 -c 2 -c 1
