language: python
python:
  - "2.7"

# command to install dependencies
install: 
  - "pip install -r requirements.txt"

# command to run tests
script: 
  - cd src
  - python clockrate.py
  - python clockrate.py -i 'for-loop' -d 5 -t 1